FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt pymysql

COPY . .

# Copiar archivos de datos iniciales al root del contenedor para que
# el script `app.scripts.load_initial_data` pueda leerlos fácilmente.
COPY canchas.json /canchas.json
COPY reservas.json /reservas.json
COPY feedbacks.json /feedbacks.json

# Copiar script de espera y dar permisos de ejecución
COPY wait-for-db.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh

EXPOSE 8000

CMD ["/wait-for-db.sh"]
