"""Initial migration: create all tables

Revision ID: 33d457cbc626
Revises: 
Create Date: 2025-11-08 18:09:34.950563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d457cbc626'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deportes',
    sa.Column('id_deporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_deporte')
    )
    op.create_index(op.f('ix_deportes_id_deporte'), 'deportes', ['id_deporte'], unique=False)
    op.create_index(op.f('ix_deportes_nombre'), 'deportes', ['nombre'], unique=True)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=False)
    op.create_table('canchas',
    sa.Column('id_cancha', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_deporte', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('precio_hora', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'MANTENIMIENTO', 'INACTIVA', name='estadocancha'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['id_deporte'], ['deportes.id_deporte'], ),
    sa.PrimaryKeyConstraint('id_cancha')
    )
    op.create_index(op.f('ix_canchas_codigo'), 'canchas', ['codigo'], unique=True)
    op.create_index(op.f('ix_canchas_estado'), 'canchas', ['estado'], unique=False)
    op.create_index(op.f('ix_canchas_id_cancha'), 'canchas', ['id_cancha'], unique=False)
    op.create_index(op.f('ix_canchas_id_deporte'), 'canchas', ['id_deporte'], unique=False)
    op.create_table('horarios_disponibles',
    sa.Column('id_horario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cancha', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False, comment='0=Domingo, 6=Sábado'),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('dia_semana >= 0 AND dia_semana <= 6', name='check_dia_semana'),
    sa.ForeignKeyConstraint(['id_cancha'], ['canchas.id_cancha'], ),
    sa.PrimaryKeyConstraint('id_horario')
    )
    op.create_index(op.f('ix_horarios_disponibles_dia_semana'), 'horarios_disponibles', ['dia_semana'], unique=False)
    op.create_index(op.f('ix_horarios_disponibles_id_cancha'), 'horarios_disponibles', ['id_cancha'], unique=False)
    op.create_index(op.f('ix_horarios_disponibles_id_horario'), 'horarios_disponibles', ['id_horario'], unique=False)
    op.create_table('reservas',
    sa.Column('id_reserva', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cancha', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('duracion', sa.Integer(), nullable=False, comment='Duración en minutos'),
    sa.Column('estado', sa.Enum('RESERVADA', 'CANCELADA', 'COMPLETADA', name='estadoreserva'), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('fecha_cancelacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cancha'], ['canchas.id_cancha'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva'),
    sa.UniqueConstraint('id_cancha', 'fecha', 'hora', name='unique_reserva')
    )
    op.create_index(op.f('ix_reservas_estado'), 'reservas', ['estado'], unique=False)
    op.create_index(op.f('ix_reservas_fecha'), 'reservas', ['fecha'], unique=False)
    op.create_index(op.f('ix_reservas_id_cancha'), 'reservas', ['id_cancha'], unique=False)
    op.create_index(op.f('ix_reservas_id_reserva'), 'reservas', ['id_reserva'], unique=False)
    op.create_index(op.f('ix_reservas_id_usuario'), 'reservas', ['id_usuario'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id_feedback', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_cancha', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='check_calificacion'),
    sa.ForeignKeyConstraint(['id_cancha'], ['canchas.id_cancha'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id_reserva'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_feedback'),
    sa.UniqueConstraint('id_reserva')
    )
    op.create_index(op.f('ix_feedbacks_calificacion'), 'feedbacks', ['calificacion'], unique=False)
    op.create_index(op.f('ix_feedbacks_fecha'), 'feedbacks', ['fecha'], unique=False)
    op.create_index(op.f('ix_feedbacks_id_cancha'), 'feedbacks', ['id_cancha'], unique=False)
    op.create_index(op.f('ix_feedbacks_id_feedback'), 'feedbacks', ['id_feedback'], unique=False)
    op.create_index(op.f('ix_feedbacks_id_usuario'), 'feedbacks', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_id_usuario'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id_feedback'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id_cancha'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_fecha'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_calificacion'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_reservas_id_usuario'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id_reserva'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_id_cancha'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_fecha'), table_name='reservas')
    op.drop_index(op.f('ix_reservas_estado'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_horarios_disponibles_id_horario'), table_name='horarios_disponibles')
    op.drop_index(op.f('ix_horarios_disponibles_id_cancha'), table_name='horarios_disponibles')
    op.drop_index(op.f('ix_horarios_disponibles_dia_semana'), table_name='horarios_disponibles')
    op.drop_table('horarios_disponibles')
    op.drop_index(op.f('ix_canchas_id_deporte'), table_name='canchas')
    op.drop_index(op.f('ix_canchas_id_cancha'), table_name='canchas')
    op.drop_index(op.f('ix_canchas_estado'), table_name='canchas')
    op.drop_index(op.f('ix_canchas_codigo'), table_name='canchas')
    op.drop_table('canchas')
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id_usuario'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_deportes_nombre'), table_name='deportes')
    op.drop_index(op.f('ix_deportes_id_deporte'), table_name='deportes')
    op.drop_table('deportes')
    # ### end Alembic commands ###
